class ADC: ...
class Pin:
    IN: int
    OUT: int
    PULL_UP: int
    IRQ_FALLING: int
    def __init__(self, *args, **kwargs): ...
    def irq(self, *args, **kwargs): ...
    def on(self): ...
    def off(self): ...
    def value(self, *args, **kwargs): ...
class SPI: ...
class I2C: ...
class PWM: ...
