# Minimal stubs to quiet desktop analyzers for MicroPython-only modules
# These are intentionally incomplete and for editor type hints only.
class ADC: ...
class Pin:
    IN: int
    OUT: int
    PULL_UP: int
    IRQ_FALLING: int
    def __init__(self, *args, **kwargs): ...
    def irq(self, *args, **kwargs): ...
    def on(self): ...
    def off(self): ...
    def value(self, *args, **kwargs): ...
class SPI: ...
class I2C: ...
class PWM: ...

# machine module aliases for typing
class machine:
    ADC = ADC
    Pin = Pin
    SPI = SPI
    I2C = I2C
    PWM = PWM

# utime/time subset
class utime:
    def sleep_ms(ms: int): ...

class network: ...

# uselect minimal
class uselect:
    POLLIN: int
    def poll(*args, **kwargs): ...
