class WLAN:
    def __init__(self, *args, **kwargs): ...
    def active(self, *args, **kwargs): ...
    def connect(self, *args, **kwargs): ...
    def isconnected(self, *args, **kwargs): ...
    def ifconfig(self, *args, **kwargs): ...
